### ISSUE TITLE
Change scene to scene with no esc script attached breaks transition

### ISSUE THREAD

**Issue by dploeger** [godot-escoria/escoria-issues#182] opened 2022-03-12 19:47 UTC
**Please make sure you talk to the community before creating an issue.**

**Describe the bug**
When using the command `change_scene` to change to another scene that has no ESC script attached, the transition breaks.

**To Reproduce**
1. Have two rooms, the second one doesn't have an ESC script attached
2. Change the scene using the `change_scene` command
3. The other scene will be shown and *then* the transition in starts

**Expected behavior**
The other scene isn't visible before the transition in starts.

**Versions**
* Escoria: alpha
* Godot: 3.4.3

**Additional context**

**Comment by BHSDuncan** [comment] 2022-04-15 19:40
I believe this is now fixed and merged in `develop`. @dploeger can you please check this?

(For the record, I removed the ESC script from room02, walked from room1 to room2, and everything looked to be in order.

I also can't reproduce it from code in PR 570, but that's based on the code submitted to address issue 102.

**Comment by StraToN** [comment] 2022-04-30 17:46
Can also be tested by walking from room16 to room17 in current develop branch. No issue, I assume this is fixed, so closing this issue. Thanks!

**Closed by StraToN** 2022-04-30 17:46 UTC
Labels: bug
