### ISSUE TITLE
ESCGame#left_click_on_bg doesn’t handle character-less rooms

### ISSUE THREAD

**Issue by dploeger** [godot-escoria/escoria-issues#110] opened 2022-02-15 07:57 UTC
**Describe the bug**
In a character-less room, the method "left_click_on_bg" of ESCGame yields an error now. I guess, this is a regression from optimizing the action workflow.

**To Reproduce**
1. Create a character less room.
2. Click on the background
=> Godot breaks to the function, because player_scene is null

**Expected behavior**
Nothing happens and no error is produced.

**Comment by BHSDuncan** [comment] 2022-04-28 03:34
@dploeger unable to reproduce in `develop` as of this comment (try room 13). Can you please verify and close this ticket if you find the same? Thanks!

**Comment by ArturM** [comment] 2022-08-08 19:29
Also unable to reproduce this error in `develop`. @dploeger

**Comment by dploeger** [comment] 2022-08-12 19:21
Ah, okay. In the example game the simple mouse and 9 verbs UIs take care of character-less rooms:

(e.g.)

https://github.com/godot-escoria/escoria-demo-game/blob/881ad581bc613e1b6ebae103f0fc6e6476813161/addons/escoria-ui-9verbs/game.gd#L67

Question is, if this shouldn't also be included in ESCgame, because there character-less rooms still would result in a problem because of a NPE:

https://github.com/godot-escoria/escoria-demo-game/blob/881ad581bc613e1b6ebae103f0fc6e6476813161/addons/escoria-core/game/core-scripts/esc_game.gd#L165

**Comment by BHSDuncan** [comment] 2022-08-24 00:36
Agreed. I'll add the checks in.

**Closed** 2022-08-26 17:44 UTC
Labels: bug
